package format

// Reference schema derived from data/table_querry1.txt (INFORMATION_SCHEMA query).
// Used as fallback to fix columns the heuristic catalog scanner misses.

type refColumn struct {
	TypeName  string
	Ordinal   int
	MaxLength int // CHARACTER_MAXIMUM_LENGTH in chars; 0 = use type FixedSize
}

func sqlTypeNameToID(name string) uint16 {
	switch name {
	case "uniqueidentifier":
		return TypeUniqueIdentifier
	case "float":
		return TypeFloat
	case "real":
		return TypeReal
	case "nvarchar":
		return TypeNVarchar
	case "nchar":
		return TypeNChar
	case "ntext":
		return TypeNText
	case "int":
		return TypeInt
	case "smallint":
		return TypeSmallInt
	case "tinyint":
		return TypeTinyInt
	case "bigint":
		return TypeBigInt
	case "bit":
		return TypeBit
	case "datetime":
		return TypeDatetime
	case "image":
		return TypeImage
	case "binary":
		return TypeBinary
	case "varbinary":
		return TypeVarBinary
	case "money":
		return TypeMoney
	case "numeric":
		return TypeNumeric
	default:
		return 0
	}
}

func refMaxLengthToBytes(typeName string, charLen int) int {
	tid := sqlTypeNameToID(typeName)
	if tid == 0 {
		return 0
	}
	ti := LookupType(tid)
	if charLen == 0 || !ti.IsVariable {
		return ti.FixedSize
	}
	switch typeName {
	case "nvarchar", "nchar":
		return charLen * 2
	case "ntext":
		return ti.FixedSize
	default:
		return charLen
	}
}

func applyReferenceSchema(colMap map[struct{ table, column string }]*ColumnDef, tableSet map[string]bool) {
	refByTable := make(map[string]map[string]refColumn)
	for k, ref := range referenceSchema {
		tbl := k[0]
		if refByTable[tbl] == nil {
			refByTable[tbl] = make(map[string]refColumn)
		}
		refByTable[tbl][k[1]] = ref
	}

	// Fix typeID=0 columns and incorrect ordinals
	for k, col := range colMap {
		ref, ok := referenceSchema[[2]string{k.table, k.column}]
		if !ok {
			continue
		}
		if col.TypeID == 0 {
			col.TypeID = sqlTypeNameToID(ref.TypeName)
			col.MaxLength = refMaxLengthToBytes(ref.TypeName, ref.MaxLength)
		}
		if col.Ordinal != ref.Ordinal {
			col.Ordinal = ref.Ordinal
		}
	}

	// Add entirely missing columns
	existing := make(map[[2]string]bool)
	for k := range colMap {
		existing[[2]string{k.table, k.column}] = true
	}
	for k, ref := range referenceSchema {
		if existing[k] {
			continue
		}
		if !tableSet[k[0]] {
			continue
		}
		tid := sqlTypeNameToID(ref.TypeName)
		colMap[struct{ table, column string }{k[0], k[1]}] = &ColumnDef{
			Name:      k[1],
			TypeID:    tid,
			Ordinal:   ref.Ordinal,
			MaxLength: refMaxLengthToBytes(ref.TypeName, ref.MaxLength),
		}
	}

	// Prune ghost columns not in reference
	for k := range colMap {
		tblRef, ok := refByTable[k.table]
		if !ok {
			continue
		}
		if _, inRef := tblRef[k.column]; !inRef {
			delete(colMap, k)
		}
	}
}

var referenceSchema = map[[2]string]refColumn{
	{"AutoStepDependency", "AutoStepDependencyIdentifier"}: {"uniqueidentifier", 1, 0},
	{"AutoStepDependency", "ControllerIdentifier"}: {"uniqueidentifier", 2, 0},
	{"AutoStepDependency", "BaseVariableIdentifier"}: {"uniqueidentifier", 3, 0},
	{"AutoStepDependency", "DependentVariableIdentifier"}: {"uniqueidentifier", 4, 0},
	{"AutoStepDependency", "ReferenceVariableIdentifier"}: {"uniqueidentifier", 5, 0},
	{"AutoStepDependency", "DependencyType"}: {"nvarchar", 6, 255},
	{"BlcModel", "BlcModelIdentifier"}: {"uniqueidentifier", 1, 0},
	{"BlcModel", "RelationIdentifier"}: {"uniqueidentifier", 2, 0},
	{"BlcModel", "LoopIdentifier"}: {"uniqueidentifier", 3, 0},
	{"BlcModel", "ItemSequenceIdentifier"}: {"uniqueidentifier", 4, 0},
	{"BlcModel", "Representation"}: {"nvarchar", 5, 50},
	{"BlcModel", "IntendedMV"}: {"nvarchar", 6, 50},
	{"BlcModel", "IntendedModelLoopType"}: {"nvarchar", 7, 50},
	{"BlcModel", "Status"}: {"nvarchar", 8, 50},
	{"BlcModel", "BlcModelBlockId"}: {"uniqueidentifier", 9, 0},
	{"Blocks", "BlockIdentifier"}: {"uniqueidentifier", 1, 0},
	{"Blocks", "Name"}: {"nvarchar", 2, 32},
	{"Blocks", "Description"}: {"nvarchar", 3, 256},
	{"Blocks", "UseSameHorizonAsModel"}: {"bit", 4, 0},
	{"Blocks", "ModelHorizonInSeconds"}: {"int", 5, 0},
	{"Blocks", "PlotIntervalInSeconds"}: {"int", 6, 0},
	{"Blocks", "LargestSettlingTimeInSeconds"}: {"int", 7, 0},
	{"Blocks", "SmallestSettlingTimeInSeconds"}: {"int", 8, 0},
	{"Blocks", "ResponsePlotType"}: {"smallint", 9, 0},
	{"Blocks", "ResponsePlotScalingType"}: {"smallint", 10, 0},
	{"Blocks", "ResponsePlotElementsType"}: {"smallint", 11, 0},
	{"Blocks", "FormulaString"}: {"nvarchar", 12, 4000},
	{"Blocks", "IsFormulaValid"}: {"bit", 13, 0},
	{"Blocks", "GainUpdateMethod"}: {"smallint", 14, 0},
	{"Blocks", "GainUpdateToleranceMin"}: {"float", 15, 0},
	{"Blocks", "GainUpdateTolerancePercent"}: {"float", 16, 0},
	{"BlockVariableReferences", "BlockId"}: {"uniqueidentifier", 1, 0},
	{"BlockVariableReferences", "ProcessVariableId"}: {"uniqueidentifier", 2, 0},
	{"BlockVariableReferences", "ParentObjId"}: {"uniqueidentifier", 3, 0},
	{"BlockVariableReferences", "ReferenceType"}: {"nvarchar", 4, 32},
	{"BlockVariableReferences", "SortOrder"}: {"int", 5, 0},
	{"ChartCell", "ChartIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ChartCell", "ChartCellIdentifier"}: {"uniqueidentifier", 2, 0},
	{"ChartCell", "RowIndex"}: {"int", 3, 0},
	{"ChartCell", "ColumnIndex"}: {"int", 4, 0},
	{"Charts", "ChartIdentifier"}: {"uniqueidentifier", 1, 0},
	{"Charts", "VariablesPerPlot"}: {"int", 2, 0},
	{"Charts", "ViewRows"}: {"int", 3, 0},
	{"Charts", "ViewColumns"}: {"int", 4, 0},
	{"Charts", "FixedRows"}: {"bit", 5, 0},
	{"Charts", "FixedColumns"}: {"bit", 6, 0},
	{"Charts", "RowCounts"}: {"int", 7, 0},
	{"Charts", "ColumnCounts"}: {"int", 8, 0},
	{"Charts", "FitIdentifier"}: {"uniqueidentifier", 9, 0},
	{"CodeBlock", "ParentIdentifier"}: {"uniqueidentifier", 1, 0},
	{"CodeBlock", "CodeBlockId"}: {"uniqueidentifier", 2, 0},
	{"CodeBlock", "ItemSequenceIdentifier"}: {"uniqueidentifier", 3, 0},
	{"CodeBlock", "State"}: {"smallint", 4, 0},
	{"CodeBlockSource", "CodeBlockId"}: {"uniqueidentifier", 1, 0},
	{"CodeBlockSource", "Source"}: {"ntext", 2, 536870911},
	{"CodeBlockSource", "IsCS"}: {"bit", 3, 0},
	{"Controllers", "ControllerIdentifier"}: {"uniqueidentifier", 1, 0},
	{"Controllers", "CustomInputIoItemsSequenceCollectionId"}: {"uniqueidentifier", 2, 0},
	{"Controllers", "CustomOutputIoItemsSequenceCollectionId"}: {"uniqueidentifier", 3, 0},
	{"Controllers", "ShedLogicRuleItemsSequenceCollectionId"}: {"uniqueidentifier", 4, 0},
	{"Controllers", "SubsystemSequenceCollectionID"}: {"uniqueidentifier", 5, 0},
	{"Controllers", "EconomicFunctionSequenceCollectionID"}: {"uniqueidentifier", 6, 0},
	{"Controllers", "IsAutoNumberConstraints"}: {"bit", 7, 0},
	{"Controllers", "IsAutoSortConstraints"}: {"bit", 8, 0},
	{"Controllers", "IsAutoTestEnabled"}: {"bit", 9, 0},
	{"Controllers", "AllowSubSystems"}: {"bit", 10, 0},
	{"ControllerSubSystem", "SubSystemIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ControllerSubSystem", "ControllerIdentifier"}: {"uniqueidentifier", 2, 0},
	{"ControllerSubSystem", "ItemSequenceIdentifier"}: {"uniqueidentifier", 3, 0},
	{"ControllerSubSystem", "IsDefault"}: {"bit", 4, 0},
	{"ControllerSubSystem", "ExecutionMultiple"}: {"int", 5, 0},
	{"ControllerSubSystem", "ExecutionOffset"}: {"int", 6, 0},
	{"ControllerSubSystem", "OrderNumber"}: {"int", 7, 0},
	{"ControllerSubSystemVariableReferences", "ControllerIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ControllerSubSystemVariableReferences", "SubSystemIdentifier"}: {"uniqueidentifier", 2, 0},
	{"ControllerSubSystemVariableReferences", "ProcessVariableIdentifier"}: {"uniqueidentifier", 3, 0},
	{"ControllerSubSystemVariableReferences", "ReferenceType"}: {"nvarchar", 4, 32},
	{"ControllerVariableReference", "ControllerVariableReferenceIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ControllerVariableReference", "ParentIdentifier"}: {"uniqueidentifier", 2, 0},
	{"ControllerVariableReference", "ProcessVariableId"}: {"uniqueidentifier", 3, 0},
	{"ControllerVariableReference", "ReferenceType"}: {"nvarchar", 4, 32},
	{"ControllerVariableReference", "MV"}: {"bit", 5, 0},
	{"ControllerVariableReference", "CV"}: {"bit", 6, 0},
	{"CustomCode", "CustomCodeIdentifier"}: {"uniqueidentifier", 1, 0},
	{"CustomCode", "ProcessorIdentifier"}: {"uniqueidentifier", 2, 0},
	{"CustomCode", "ExecutionType"}: {"smallint", 3, 0},
	{"CustomProcessor", "CustomProcessorIdentifier"}: {"uniqueidentifier", 1, 0},
	{"CustomProcessor", "CustomInputIoItemsSequenceCollectionId"}: {"uniqueidentifier", 2, 0},
	{"CustomProcessor", "CustomOutputIoItemsSequenceCollectionId"}: {"uniqueidentifier", 3, 0},
	{"CustomProcessor", "ShedLogicRuleItemsSequenceCollectionId"}: {"uniqueidentifier", 4, 0},
	{"CustomProcessor", "CodeBlockSequenceCollectionID"}: {"uniqueidentifier", 5, 0},
	{"CVRole", "CVRoleIdentifier"}: {"uniqueidentifier", 1, 0},
	{"CVRole", "IsLoLimitSpec"}: {"bit", 2, 0},
	{"CVRole", "IsHiLimitSpec"}: {"bit", 3, 0},
	{"CVRole", "IsSetPointSpec"}: {"bit", 4, 0},
	{"CVRole", "MinTimeToLimit"}: {"float", 5, 0},
	{"CVRole", "RampRateImbalanceLo"}: {"float", 6, 0},
	{"CVRole", "RampRateImbalanceHi"}: {"float", 7, 0},
	{"CVRole", "RampImbalanceMethod"}: {"nvarchar", 8, 50},
	{"DataArrayTypes", "Identifier"}: {"uniqueidentifier", 1, 0},
	{"DataArrayTypes", "ArrayType"}: {"nvarchar", 2, 50},
	{"DataArrayTypes", "Interval"}: {"int", 3, 0},
	{"DataArrayTypes", "Unit"}: {"nvarchar", 4, 50},
	{"DataCleanerAdHocPoint", "DataCleanerIdentifier"}: {"uniqueidentifier", 1, 0},
	{"DataCleanerAdHocPoint", "TimeStamp"}: {"datetime", 2, 0},
	{"DataCleanerAdHocPoint", "Value"}: {"real", 3, 0},
	{"DataCleanerAdHocPoint", "Quality"}: {"smallint", 4, 0},
	{"DataCleaners", "DataCleanerIdentifier"}: {"uniqueidentifier", 1, 0},
	{"DataCleaners", "DataArrayTypeIdentifier"}: {"uniqueidentifier", 2, 0},
	{"DataCleaners", "AllVariableSelected"}: {"bit", 3, 0},
	{"DataCleaners", "StartTimeUtc"}: {"datetime", 4, 0},
	{"DataCleaners", "EndTimeUtc"}: {"datetime", 5, 0},
	{"DataCleaners", "HighLimitValue"}: {"float", 6, 0},
	{"DataCleaners", "HighLimitEnabled"}: {"bit", 7, 0},
	{"DataCleaners", "HighClipClampType"}: {"nvarchar", 8, 128},
	{"DataCleaners", "LowLimitValue"}: {"float", 9, 0},
	{"DataCleaners", "LowLimitEnabled"}: {"bit", 10, 0},
	{"DataCleaners", "LowClipClampType"}: {"nvarchar", 11, 128},
	{"DataCleaners", "FitIdentifier"}: {"uniqueidentifier", 12, 0},
	{"DataCleanerVariableReference", "ParentObjId"}: {"uniqueidentifier", 1, 0},
	{"DataCleanerVariableReference", "ProcessVariableId"}: {"uniqueidentifier", 2, 0},
	{"DataCleanerVariableReference", "IsCustomRuleReference"}: {"bit", 3, 0},
	{"DataLinks", "DataLinkIdentifier"}: {"uniqueidentifier", 1, 0},
	{"DataLinks", "Source"}: {"uniqueidentifier", 2, 0},
	{"DataLinks", "Destination"}: {"uniqueidentifier", 3, 0},
	{"DataLinks", "Ownership"}: {"nvarchar", 4, 32},
	{"DataSlice", "DataSliceIdentifier"}: {"uniqueidentifier", 1, 0},
	{"DataSlice", "ControllerIdentifier"}: {"uniqueidentifier", 2, 0},
	{"DataSlice", "VariableSetIdentifier"}: {"uniqueidentifier", 3, 0},
	{"DataSlice", "StartTimeUtc"}: {"datetime", 4, 0},
	{"DataSlice", "EndTimeUtc"}: {"datetime", 5, 0},
	{"DataSlice", "Description"}: {"nvarchar", 6, 255},
	{"DesigntimeParameters", "ItemIdentifier"}: {"uniqueidentifier", 1, 0},
	{"DesigntimeParameters", "Name"}: {"nvarchar", 2, 64},
	{"DesigntimeParameters", "Value"}: {"ntext", 3, 536870911},
	{"DigitalMaps", "DigitalMapIdentifier"}: {"uniqueidentifier", 1, 0},
	{"DigitalMaps", "DigitalTypeIdentifier"}: {"uniqueidentifier", 2, 0},
	{"DigitalMaps", "DefaultDigitalStateIdentifier"}: {"uniqueidentifier", 3, 0},
	{"DigitalMapTranslations", "DigitalMapTranslationIdentifier"}: {"uniqueidentifier", 1, 0},
	{"DigitalMapTranslations", "DigitalMapIdentifier"}: {"uniqueidentifier", 2, 0},
	{"DigitalMapTranslations", "ProcessValue"}: {"nvarchar", 3, 128},
	{"DigitalMapTranslations", "DigitalStateIdentifier"}: {"uniqueidentifier", 4, 0},
	{"DigitalMapTranslations", "ItemOrder"}: {"smallint", 5, 0},
	{"DigitalStates", "DigitalStateIdentifier"}: {"uniqueidentifier", 1, 0},
	{"DigitalStates", "DigitalTypeIdentifier"}: {"uniqueidentifier", 2, 0},
	{"DigitalStates", "Name"}: {"nvarchar", 3, 128},
	{"DigitalStates", "Value"}: {"int", 4, 0},
	{"DVRole", "DVRoleIdentifier"}: {"uniqueidentifier", 1, 0},
	{"EconomicFunction", "EconomicFunctionIdentifier"}: {"uniqueidentifier", 1, 0},
	{"EconomicFunction", "ControllerIdentifier"}: {"uniqueidentifier", 2, 0},
	{"EconomicFunction", "ItemSequenceIdentifier"}: {"uniqueidentifier", 3, 0},
	{"EconomicFunction", "FormulaString"}: {"nvarchar", 4, 4000},
	{"EconomicFunction", "IsFormulaValid"}: {"bit", 5, 0},
	{"Estimators", "EstimatorIdentifier"}: {"uniqueidentifier", 1, 0},
	{"Estimators", "CustomInputIoItemsSequenceCollectionId"}: {"uniqueidentifier", 2, 0},
	{"Estimators", "CustomOutputIoItemsSequenceCollectionId"}: {"uniqueidentifier", 3, 0},
	{"Estimators", "ShedLogicRuleItemsSequenceCollectionId"}: {"uniqueidentifier", 4, 0},
	{"Estimators", "ModelIdentifier"}: {"uniqueidentifier", 5, 0},
	{"Estimators", "ExecutionMultiple"}: {"int", 6, 0},
	{"Estimators", "VariableSetSequenceCollectionID"}: {"uniqueidentifier", 7, 0},
	{"Estimators", "IsAdvancedEstimationEnabled"}: {"bit", 8, 0},
	{"EstimatorVariableSet", "VariableSetIdentifier"}: {"uniqueidentifier", 1, 0},
	{"EstimatorVariableSet", "Hide"}: {"bit", 2, 0},
	{"EstimatorVariableSet", "EstimatorIdentifier"}: {"uniqueidentifier", 3, 0},
	{"EstimatorVariableSet", "ItemSequenceIdentifier"}: {"uniqueidentifier", 4, 0},
	{"EstimatorVariableSet", "IsDefault"}: {"bit", 5, 0},
	{"EstimatorVariableSet", "Modes"}: {"bit", 6, 0},
	{"EstimatorVariableSet", "Maintenance"}: {"bit", 7, 0},
	{"EstimatorVariableSet", "Control"}: {"bit", 8, 0},
	{"EstimatorVariableSet", "Test"}: {"bit", 9, 0},
	{"EstimatorVariableSet", "OrderNumber"}: {"int", 10, 0},
	{"EstimatorVariableSet", "VariableCVCollectionID"}: {"uniqueidentifier", 11, 0},
	{"EstimatorVariableSet", "VariableMVCollectionID"}: {"uniqueidentifier", 12, 0},
	{"EstimatorVariableSet", "VariableDVCollectionID"}: {"uniqueidentifier", 13, 0},
	{"EstimatorVariableSet", "VariablePOVCollectionID"}: {"uniqueidentifier", 14, 0},
	{"EstimatorVariableSetMember", "EstimatorVariableSetMemberIdentifier"}: {"uniqueidentifier", 1, 0},
	{"EstimatorVariableSetMember", "VariableSetIdentifier"}: {"uniqueidentifier", 2, 0},
	{"EstimatorVariableSetMember", "VariableRoleIdentifier"}: {"uniqueidentifier", 3, 0},
	{"EstimatorVariableSetMember", "ItemSequenceIdentifier"}: {"uniqueidentifier", 4, 0},
	{"EstimatorVariableSetMember", "Hide"}: {"bit", 5, 0},
	{"EstimatorVariableSetMember", "Maintenance"}: {"bit", 6, 0},
	{"EstimatorVariableSetMember", "Managed"}: {"bit", 7, 0},
	{"EstimatorVariableSetMember", "Auto"}: {"bit", 8, 0},
	{"ExecutionSequence", "ExecutionSequenceIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ExecutionSequence", "IsDefault"}: {"bit", 2, 0},
	{"ExecutionSequence", "ExecutionIntervalInMilliseconds"}: {"int", 3, 0},
	{"ExternalRuntimeDataSource", "ExternalRuntimeDataSourceIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ExternalRuntimeDataSource", "ItemSequenceIdentifier"}: {"uniqueidentifier", 2, 0},
	{"ExternalRuntimeDataSource", "FailureBehavior"}: {"nvarchar", 3, 32},
	{"ExternalRuntimeDataSource", "ReadWriteFailureLimit"}: {"int", 4, 0},
	{"ExternalRuntimeDataSource", "IsDefault"}: {"bit", 5, 0},
	{"FIRElements", "FIRElementIdentifier"}: {"uniqueidentifier", 1, 0},
	{"FIRElements", "IsRamp"}: {"bit", 2, 0},
	{"FIRElements", "DelayTime"}: {"float", 3, 0},
	{"FIRElements", "SettlingTime"}: {"float", 4, 0},
	{"FIRElements", "FitStat"}: {"float", 5, 0},
	{"FitBlocks", "FitBlockIdentifier"}: {"uniqueidentifier", 1, 0},
	{"FitBlocks", "ParentFitId"}: {"uniqueidentifier", 2, 0},
	{"FitBlocks", "PlaceHolder"}: {"int", 3, 0},
	{"FitCharts", "FitIdentifier"}: {"uniqueidentifier", 1, 0},
	{"FitCharts", "ChartIdentifier"}: {"uniqueidentifier", 2, 0},
	{"FitCharts", "FitChartLayout"}: {"nvarchar", 3, 32},
	{"FitGroupReferences", "GroupIdentifier"}: {"uniqueidentifier", 1, 0},
	{"FitGroupReferences", "ItemIdentifier"}: {"uniqueidentifier", 2, 0},
	{"FitGroupReferences", "InputIdentifier"}: {"uniqueidentifier", 3, 0},
	{"FitGroupReferences", "OutputIdentifier"}: {"uniqueidentifier", 4, 0},
	{"FitParametricElements", "FitElementIdentifier"}: {"uniqueidentifier", 1, 0},
	{"FitParametricElements", "IsGainFixed"}: {"bit", 2, 0},
	{"FitParametricElements", "GainLoLimit"}: {"float", 3, 0},
	{"FitParametricElements", "GainHiLimit"}: {"float", 4, 0},
	{"FitParametricElements", "GainConfidenceLo"}: {"float", 5, 0},
	{"FitParametricElements", "GainConfidenceHi"}: {"float", 6, 0},
	{"FitParametricElements", "IsDelayFixed"}: {"bit", 7, 0},
	{"FitParametricElements", "DelayLoLimit"}: {"float", 8, 0},
	{"FitParametricElements", "DelayHiLimit"}: {"float", 9, 0},
	{"FitParametricElements", "DelayConfidenceLo"}: {"float", 10, 0},
	{"FitParametricElements", "DelayConfidenceHi"}: {"float", 11, 0},
	{"FitParametricElements", "IsTau1Fixed"}: {"bit", 12, 0},
	{"FitParametricElements", "Tau1LoLimit"}: {"float", 13, 0},
	{"FitParametricElements", "Tau1HiLimit"}: {"float", 14, 0},
	{"FitParametricElements", "Tau1ConfidenceLo"}: {"float", 15, 0},
	{"FitParametricElements", "Tau1ConfidenceHi"}: {"float", 16, 0},
	{"FitParametricElements", "IsTau2Fixed"}: {"bit", 17, 0},
	{"FitParametricElements", "Tau2LoLimit"}: {"float", 18, 0},
	{"FitParametricElements", "Tau2HiLimit"}: {"float", 19, 0},
	{"FitParametricElements", "Tau2ConfidenceLo"}: {"float", 20, 0},
	{"FitParametricElements", "Tau2ConfidenceHi"}: {"float", 21, 0},
	{"FitParametricElements", "IsBetaFixed"}: {"bit", 22, 0},
	{"FitParametricElements", "BetaLoLimit"}: {"float", 23, 0},
	{"FitParametricElements", "BetaHiLimit"}: {"float", 24, 0},
	{"FitParametricElements", "BetaConfidenceLo"}: {"float", 25, 0},
	{"FitParametricElements", "BetaConfidenceHi"}: {"float", 26, 0},
	{"FitParametricElements", "AdequacyKpi"}: {"float", 27, 0},
	{"FitParametricElements", "VisibilityKpi"}: {"float", 28, 0},
	{"FitParametricElements", "MismatchKpi"}: {"float", 29, 0},
	{"FitParametricElements", "ValidationDiagnostic"}: {"int", 30, 0},
	{"Fits", "FitIdentifier"}: {"uniqueidentifier", 1, 0},
	{"Fits", "IsFitModelTypeDynamic"}: {"bit", 2, 0},
	{"Fits", "IsFitModelTypeMISO"}: {"bit", 3, 0},
	{"Fits", "IsFitModelTypePCAPLS"}: {"bit", 4, 0},
	{"Fits", "ResampleMultiple"}: {"int", 5, 0},
	{"Fits", "PerformCompaction"}: {"bit", 6, 0},
	{"Fits", "InitialConditionOnSteadyState"}: {"bit", 7, 0},
	{"Fits", "CheckInputDependence"}: {"bit", 8, 0},
	{"Fits", "SelectionType"}: {"nvarchar", 9, 32},
	{"Fits", "IsAutoIncludeSignificantRelationship"}: {"bit", 10, 0},
	{"Fits", "SignificanceThreshold"}: {"float", 11, 0},
	{"Fits", "MaxDelay"}: {"float", 12, 0},
	{"Fits", "DifferenceFilter"}: {"int", 13, 0},
	{"Fits", "ClosedLoop"}: {"bit", 14, 0},
	{"Fits", "ComputeFIRConfidence"}: {"bit", 15, 0},
	{"Fits", "ModelHorizonInSeconds"}: {"int", 16, 0},
	{"Fits", "SsdIsDirty"}: {"bit", 17, 0},
	{"FitSisoPairs", "FitSisoPairIdentifier"}: {"uniqueidentifier", 1, 0},
	{"FitSisoPairs", "FitIdentifier"}: {"uniqueidentifier", 2, 0},
	{"FitSisoPairs", "Significance"}: {"float", 3, 0},
	{"FitSisoPairs", "SignificanceRank"}: {"int", 4, 0},
	{"FitSisoPairs", "EstimatedDelay"}: {"float", 5, 0},
	{"FitSisoPairs", "InputVariableReference"}: {"uniqueidentifier", 6, 0},
	{"FitSisoPairs", "OutputVariableReference"}: {"uniqueidentifier", 7, 0},
	{"FitSteadyState", "ProcessVariableReferenceIdentifier"}: {"uniqueidentifier", 1, 0},
	{"FitSteadyState", "FitIdentifier"}: {"uniqueidentifier", 2, 0},
	{"FitSteadyState", "PositionIndex"}: {"int", 3, 0},
	{"FitSteadyState", "BreakPoint"}: {"int", 4, 0},
	{"FitSteadyState", "SteadyValue"}: {"float", 5, 0},
	{"FitSteadyState", "IsSteady"}: {"bit", 6, 0},
	{"FitSteadyState", "TimeStamp"}: {"datetime", 7, 0},
	{"FitVariableReference", "RelationVariableReferenceIdentifier"}: {"uniqueidentifier", 1, 0},
	{"FitVariableReference", "EstimationFIRAccuracyKPI"}: {"float", 2, 0},
	{"FitVariableReference", "EstimationF2PAccuracyKPI"}: {"float", 3, 0},
	{"FitVariableReference", "EstimationPARAccuracyKPI"}: {"float", 4, 0},
	{"FitVariableReference", "ValidationFIRAccuracyKPI"}: {"float", 5, 0},
	{"FitVariableReference", "ValidationF2PAccuracyKPI"}: {"float", 6, 0},
	{"FitVariableReference", "ValidationPARAccuracyKPI"}: {"float", 7, 0},
	{"FitVariableReference", "IsDriftDetectionEnabled"}: {"bit", 8, 0},
	{"FitVariableReference", "IsNoImmediateResponseEnabled"}: {"bit", 9, 0},
	{"FitVariableReference", "PrefilterHorizonInMinutes"}: {"int", 10, 0},
	{"FitVariableReference", "PredictionHorizonInMinutes"}: {"int", 11, 0},
	{"FitVariableReference", "Threshold"}: {"float", 12, 0},
	{"FitVariableReference", "SampleTimeShift"}: {"int", 13, 0},
	{"FitVariableReference", "SSDWindow"}: {"int", 14, 0},
	{"FitVariableReference", "LV"}: {"int", 15, 0},
	{"FitVariableReference", "ZoomMinValue"}: {"float", 16, 0},
	{"FitVariableReference", "ZoomMaxValue"}: {"float", 17, 0},
	{"FitVariableReference", "Numerator"}: {"nvarchar", 18, 420},
	{"FitVariableReference", "Denominator"}: {"nvarchar", 19, 420},
	{"FormulaInputProcessVariableReference", "ParentObjId"}: {"uniqueidentifier", 1, 0},
	{"FormulaInputProcessVariableReference", "InputProcessVariableId"}: {"uniqueidentifier", 2, 0},
	{"FormulaInputProcessVariableReference", "UsedInFormula"}: {"bit", 3, 0},
	{"FormulaInputUserParameterReference", "ParentObjId"}: {"uniqueidentifier", 1, 0},
	{"FormulaInputUserParameterReference", "UserParameterId"}: {"uniqueidentifier", 2, 0},
	{"FormulaInputUserParameterReference", "UsedInFormula"}: {"bit", 3, 0},
	{"GroupOrder", "GroupIdentifier"}: {"uniqueidentifier", 1, 0},
	{"GroupOrder", "GroupOrder"}: {"int", 2, 0},
	{"GroupReferences", "GroupIdentifier"}: {"uniqueidentifier", 1, 0},
	{"GroupReferences", "ItemIdentifier"}: {"uniqueidentifier", 2, 0},
	{"GroupReferences", "ItemOrder"}: {"int", 3, 0},
	{"IOItems", "IOItemIdentifier"}: {"uniqueidentifier", 1, 0},
	{"IOItems", "IOItemType"}: {"nvarchar", 2, 32},
	{"IOItems", "Reference"}: {"nvarchar", 3, 255},
	{"IOItems", "RuntimeDataSourceIdentifier"}: {"uniqueidentifier", 4, 0},
	{"IOItems", "ReferencerType"}: {"nvarchar", 5, 32},
	{"IOItems", "IsExternal"}: {"bit", 6, 0},
	{"IOItems", "IsInput"}: {"bit", 7, 0},
	{"IOItems", "DataType"}: {"nvarchar", 8, 16},
	{"IOItems", "ParameterName"}: {"nvarchar", 9, 50},
	{"IOItems", "Value"}: {"nvarchar", 10, 32},
	{"IOItems", "ReferencerIdentifier"}: {"uniqueidentifier", 11, 0},
	{"IOItems", "DigitalTypeIdentifier"}: {"uniqueidentifier", 12, 0},
	{"IOMap", "Identifier"}: {"uniqueidentifier", 1, 0},
	{"IOMap", "ItemSequenceIdentifier"}: {"uniqueidentifier", 2, 0},
	{"IOMap", "ExternalRuntimeDataSourceIdentifier"}: {"uniqueidentifier", 3, 0},
	{"IOMap", "Prefix"}: {"nvarchar", 4, 32},
	{"IOMapNonExistingLinkLock", "Identifier"}: {"uniqueidentifier", 1, 0},
	{"IOMapNonExistingLinkLock", "IOMapId"}: {"uniqueidentifier", 2, 0},
	{"IOMapNonExistingLinkLock", "IOItemId"}: {"uniqueidentifier", 3, 0},
	{"IOMapNonExistingLinkLock", "Direction"}: {"nvarchar", 4, 32},
	{"IOMapRule", "Identifier"}: {"uniqueidentifier", 1, 0},
	{"IOMapRule", "Enabled"}: {"bit", 2, 0},
	{"IOMapRule", "IOMapId"}: {"uniqueidentifier", 3, 0},
	{"IOMapRule", "ReferencerType"}: {"nvarchar", 4, 32},
	{"IOMapRule", "ParameterName"}: {"nvarchar", 5, 256},
	{"IOMapRule", "Direction"}: {"nvarchar", 6, 32},
	{"IOMapRule", "Pattern"}: {"nvarchar", 7, 2048},
	{"IOMapRule", "Attribute"}: {"nvarchar", 8, 1024},
	{"IOMapRule", "Format"}: {"nvarchar", 9, 1024},
	{"ItemInformation", "Identifier"}: {"uniqueidentifier", 1, 0},
	{"ItemInformation", "Name"}: {"nvarchar", 2, 32},
	{"ItemInformation", "Description"}: {"nvarchar", 3, 256},
	{"ItemInformation", "Notes"}: {"nvarchar", 4, 2048},
	{"ItemInformation", "Type"}: {"nvarchar", 5, 32},
	{"ItemInformation", "Virtual"}: {"bit", 6, 0},
	{"ItemSequence", "ItemSequenceIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ItemSequence", "SequenceCollectionIdentifier"}: {"uniqueidentifier", 2, 0},
	{"ItemSequence", "Sequence"}: {"int", 3, 0},
	{"ItemSequence", "ModifyTransactionIdentifier"}: {"uniqueidentifier", 4, 0},
	{"Loop", "LoopIdentifier"}: {"uniqueidentifier", 1, 0},
	{"Loop", "PV"}: {"uniqueidentifier", 2, 0},
	{"Loop", "SP"}: {"uniqueidentifier", 3, 0},
	{"Loop", "OP"}: {"uniqueidentifier", 4, 0},
	{"Loop", "MODE"}: {"uniqueidentifier", 5, 0},
	{"Loop", "INIT"}: {"uniqueidentifier", 6, 0},
	{"Loop", "Ranking"}: {"nvarchar", 7, 50},
	{"Loop", "DCSSystem"}: {"nvarchar", 8, 50},
	{"Loop", "PIDAlgorithm"}: {"nvarchar", 9, 50},
	{"Loop", "PIDForm"}: {"nvarchar", 10, 50},
	{"Loop", "PIDEquation"}: {"nvarchar", 11, 50},
	{"Loop", "LoopStatus"}: {"nvarchar", 12, 50},
	{"Loop", "PVTrack"}: {"bit", 13, 0},
	{"Loop", "SlaveLoop"}: {"uniqueidentifier", 14, 0},
	{"LoopTuningParmeter", "LoopTuningParmeterID"}: {"uniqueidentifier", 1, 0},
	{"LoopTuningParmeter", "LoopIdentifier"}: {"uniqueidentifier", 2, 0},
	{"LoopTuningParmeter", "IsManual"}: {"bit", 3, 0},
	{"LoopTuningParmeter", "CreatedDate"}: {"datetime", 4, 0},
	{"ModelLayerBlocks", "ModelLayerId"}: {"uniqueidentifier", 1, 0},
	{"ModelLayerBlocks", "ModelBlockId"}: {"uniqueidentifier", 2, 0},
	{"ModelLayers", "ModelLayerIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ModelLayers", "ParentModelId"}: {"uniqueidentifier", 2, 0},
	{"ModelLayers", "IsControlLayer"}: {"bit", 3, 0},
	{"Models", "ModelIdentifier"}: {"uniqueidentifier", 1, 0},
	{"Models", "ModelHorizonInSeconds"}: {"int", 2, 0},
	{"Models", "PlotIntervalInSeconds"}: {"int", 3, 0},
	{"Models", "LargestSettlingTimeInSeconds"}: {"int", 4, 0},
	{"Models", "SmallestSettlingTimeInSeconds"}: {"int", 5, 0},
	{"Models", "ResponsePlotType"}: {"smallint", 6, 0},
	{"Models", "ResponsePlotScalingType"}: {"smallint", 7, 0},
	{"Models", "ResponsePlotElementsType"}: {"smallint", 8, 0},
	{"Models", "ModelVariableSetCollectionID"}: {"uniqueidentifier", 9, 0},
	{"ModelVariableReference", "RelationVariableReferenceIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ModelVariableReference", "ControlLayerRampSource"}: {"int", 2, 0},
	{"ModelVariableReference", "EstimationLayerRampSource"}: {"int", 3, 0},
	{"ModelVariableSet", "ModelVariableSetIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ModelVariableSet", "ModelIdentifier"}: {"uniqueidentifier", 2, 0},
	{"ModelVariableSet", "ItemSequenceIdentifier"}: {"uniqueidentifier", 3, 0},
	{"ModelVariableSet", "ModelVariableSetInputCollectionID"}: {"uniqueidentifier", 4, 0},
	{"ModelVariableSet", "ModelVariableSetOutputCollectionID"}: {"uniqueidentifier", 5, 0},
	{"ModelVariableSet", "IsDefault"}: {"bit", 6, 0},
	{"ModelVariableSetMember", "ModelVariableSetIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ModelVariableSetMember", "ModelVariableSetMemberType"}: {"nvarchar", 2, 32},
	{"ModelVariableSetMember", "ItemSequenceIdentifier"}: {"uniqueidentifier", 3, 0},
	{"ModelVariableSetMember", "VariableReferenceIdentifier"}: {"uniqueidentifier", 4, 0},
	{"MVCVRelationship", "ControllerIdentifier"}: {"uniqueidentifier", 1, 0},
	{"MVCVRelationship", "MVRoleIdentifier"}: {"uniqueidentifier", 2, 0},
	{"MVCVRelationship", "CVRoleIdentifier"}: {"uniqueidentifier", 3, 0},
	{"MVCVRelationship", "ControllerAction"}: {"nvarchar", 4, 50},
	{"MVRole", "MVRoleIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ParametricElementLinks", "ModelIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ParametricElementLinks", "ModelElementIdentifier"}: {"uniqueidentifier", 2, 0},
	{"ParametricElementLinks", "FitIdentifier"}: {"uniqueidentifier", 3, 0},
	{"ParametricElementLinks", "FitElementIdentifier"}: {"uniqueidentifier", 4, 0},
	{"ParametricElementLinks", "IsAutoSynchEnabled"}: {"bit", 5, 0},
	{"ParametricElements", "ElementIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ParametricElements", "IsActive"}: {"bit", 2, 0},
	{"ParametricElements", "TransferFunction"}: {"nvarchar", 3, 50},
	{"ParametricElements", "Delay"}: {"float", 4, 0},
	{"ParametricElements", "Gain"}: {"float", 5, 0},
	{"ParametricElements", "Tau1"}: {"float", 6, 0},
	{"ParametricElements", "Tau2"}: {"float", 7, 0},
	{"ParametricElements", "Beta"}: {"float", 8, 0},
	{"ParametricElements", "UncertaintyZoneTau"}: {"float", 9, 0},
	{"ParametricElements", "UncertaintyZoneBeta"}: {"float", 10, 0},
	{"ParametricElements", "BetaXGain"}: {"float", 11, 0},
	{"ParametricElements", "UnitMinY"}: {"float", 12, 0},
	{"ParametricElements", "UnitMaxY"}: {"float", 13, 0},
	{"ParametricElements", "SettlingTimeInSeconds"}: {"int", 14, 0},
	{"ParametricElements", "SamplingTime"}: {"real", 15, 0},
	{"ParametricElements", "SettlingTimePlot"}: {"real", 16, 0},
	{"ParametricElements", "SettlingTimeControl"}: {"real", 17, 0},
	{"POVRole", "POVRoleIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ProcessorCustomIoItem", "ProcessorIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ProcessorCustomIoItem", "IOItemIdentifier"}: {"uniqueidentifier", 2, 0},
	{"ProcessorCustomIoItem", "Description"}: {"nvarchar", 3, 255},
	{"ProcessorCustomIoItem", "Name"}: {"nvarchar", 4, 32},
	{"ProcessorCustomIoItem", "ItemSequenceIdentifier"}: {"uniqueidentifier", 5, 0},
	{"ProcessorInExecutionSequence", "ExecutionSequenceIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ProcessorInExecutionSequence", "ProcessorIdentifier"}: {"uniqueidentifier", 2, 0},
	{"ProcessorInExecutionSequence", "ItemSequenceIdentifier"}: {"uniqueidentifier", 3, 0},
	{"ProcessorInExecutionSequence", "ExecutionMultiple"}: {"int", 4, 0},
	{"ProcessorInExecutionSequence", "ExecutionOffset"}: {"int", 5, 0},
	{"Processors", "ProcessorIdentifier"}: {"uniqueidentifier", 1, 0},
	{"Processors", "ModifiedDate"}: {"datetime", 2, 0},
	{"ProcessorShedLogicRuleItem", "ShedLogicRuleItemIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ProcessorShedLogicRuleItem", "ProcessorIdentifier"}: {"uniqueidentifier", 2, 0},
	{"ProcessorShedLogicRuleItem", "ItemSequenceIdentifier"}: {"uniqueidentifier", 3, 0},
	{"ProcessorShedLogicRuleItem", "Pulsed"}: {"bit", 4, 0},
	{"ProcessorShedLogicRuleItem", "TestIOItemIdentifier"}: {"uniqueidentifier", 5, 0},
	{"ProcessorShedLogicRuleItem", "ComparisonOperatorType"}: {"nvarchar", 6, 128},
	{"ProcessorShedLogicRuleItem", "ComparisonValueType"}: {"nvarchar", 7, 128},
	{"ProcessorShedLogicRuleItem", "ComparisonValue"}: {"nvarchar", 8, 128},
	{"ProcessorShedLogicRuleItem", "ComparisonIOItemIdentifier"}: {"uniqueidentifier", 9, 0},
	{"ProcessorShedLogicRuleItem", "ShedLogicIOItemIdentifier"}: {"uniqueidentifier", 10, 0},
	{"ProcessorShedLogicRuleItem", "ShedLogicValue"}: {"nvarchar", 11, 128},
	{"ProcessVariables", "ProcessVariableIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ProcessVariables", "EngineeringUnits"}: {"nvarchar", 2, 32},
	{"ProcessVariables", "DigitalTypeIdentifier"}: {"uniqueidentifier", 3, 0},
	{"ProcessVariables", "DigitalMapIdentifier"}: {"uniqueidentifier", 4, 0},
	{"ProcessVariables", "IsDigitalDataType"}: {"bit", 5, 0},
	{"ProcessVariables", "NormalMove"}: {"float", 6, 0},
	{"ProcessVariables", "FormulaString"}: {"nvarchar", 7, 4000},
	{"ProcessVariables", "IsFormulaValid"}: {"bit", 8, 0},
	{"ProcessVariables", "MeasurementType"}: {"nvarchar", 9, 32},
	{"ProcessVariables", "IsAutoDetectNewValue"}: {"bit", 10, 0},
	{"Properties", "Name"}: {"nvarchar", 1, 32},
	{"Properties", "Value"}: {"nvarchar", 2, 256},
	{"Relation", "RelationIdentifier"}: {"uniqueidentifier", 1, 0},
	{"Relation", "InputVariableCollectionID"}: {"uniqueidentifier", 2, 0},
	{"Relation", "OutputVariableCollectionID"}: {"uniqueidentifier", 3, 0},
	{"Relation", "RelationLoopsCollectionID"}: {"uniqueidentifier", 4, 0},
	{"Relation", "ModifiedDate"}: {"datetime", 5, 0},
	{"RelationBlocks", "RelationBlockIdentifier"}: {"uniqueidentifier", 1, 0},
	{"RelationBlocks", "RelationIdentifier"}: {"uniqueidentifier", 2, 0},
	{"RelationBlocks", "BlockType"}: {"nvarchar", 3, 32},
	{"RelationBlocks", "IsMultiElement"}: {"bit", 4, 0},
	{"RelationVariableReference", "RelationVariableReferenceIdentifier"}: {"uniqueidentifier", 1, 0},
	{"RelationVariableReference", "ParentType"}: {"nvarchar", 2, 32},
	{"RelationVariableReference", "VariableReferenceIdentifier"}: {"uniqueidentifier", 3, 0},
	{"RTOControllers", "RTOInterfaceControllerIdentifier"}: {"uniqueidentifier", 1, 0},
	{"RTOControllers", "RTOInterfaceIdentifier"}: {"uniqueidentifier", 2, 0},
	{"RTOControllers", "ControllerIdentifier"}: {"uniqueidentifier", 3, 0},
	{"RTOControllers", "ItemSequenceIdentifier"}: {"uniqueidentifier", 4, 0},
	{"RTOControllers", "VariableRoleSequenceCollectionID"}: {"uniqueidentifier", 5, 0},
	{"RTOInterface", "RTOInterfaceIdentifier"}: {"uniqueidentifier", 1, 0},
	{"RTOInterface", "CustomInputIoItemsSequenceCollectionId"}: {"uniqueidentifier", 2, 0},
	{"RTOInterface", "CustomOutputIoItemsSequenceCollectionId"}: {"uniqueidentifier", 3, 0},
	{"RTOInterface", "ShedLogicRuleItemsSequenceCollectionId"}: {"uniqueidentifier", 4, 0},
	{"RTOInterface", "RTOControllersSequenceCollectionID"}: {"uniqueidentifier", 5, 0},
	{"RTOInterface", "RTOVariableRolesSequenceCollectionID"}: {"uniqueidentifier", 6, 0},
	{"RTOVariableRoles", "RTOVariableRoleIdentifier"}: {"uniqueidentifier", 1, 0},
	{"RTOVariableRoles", "RTOInterfaceControllerIdentifier"}: {"uniqueidentifier", 2, 0},
	{"RTOVariableRoles", "RoleIdentifier"}: {"uniqueidentifier", 3, 0},
	{"RTOVariableRoles", "ItemSequenceIdentifier"}: {"uniqueidentifier", 4, 0},
	{"ScenarioStep", "ScenarioIdentifier"}: {"uniqueidentifier", 1, 0},
	{"ScenarioStep", "ItemSequenceIdentifier"}: {"uniqueidentifier", 2, 0},
	{"ScenarioStep", "WaitTime"}: {"float", 3, 0},
	{"ScenarioStep", "Duration"}: {"float", 4, 0},
	{"ScenarioStep", "Operation"}: {"tinyint", 5, 0},
	{"ScenarioStep", "IsEnabled"}: {"bit", 6, 0},
	{"ScenarioStep", "NewValue"}: {"nvarchar", 7, 32},
	{"ScenarioStep", "IOItemIdentifier"}: {"uniqueidentifier", 8, 0},
	{"SimulationCase", "CaseIdentifier"}: {"uniqueidentifier", 1, 0},
	{"SimulationCase", "ScenarioIdentifier"}: {"uniqueidentifier", 2, 0},
	{"SimulationCase", "SequenceIdentifier"}: {"uniqueidentifier", 3, 0},
	{"SimulationCase", "IsEnabled"}: {"bit", 4, 0},
	{"SimulationCase", "SyncWithProcessModel"}: {"bit", 5, 0},
	{"SimulationCase", "StartTime"}: {"datetime", 6, 0},
	{"SimulationCaseModel", "SimulationCaseIdentifier"}: {"uniqueidentifier", 1, 0},
	{"SimulationCaseModel", "ItemSequenceIdentifier"}: {"uniqueidentifier", 2, 0},
	{"SimulationCaseModel", "ModelIdentifier"}: {"uniqueidentifier", 3, 0},
	{"SimulationCaseModel", "SelectedLayer"}: {"int", 4, 0},
	{"SimulationCaseSetup", "Identifier"}: {"uniqueidentifier", 1, 0},
	{"SimulationCaseSetup", "CaseIdentifier"}: {"uniqueidentifier", 2, 0},
	{"SimulationCaseSetup", "IOItemIdentifier"}: {"uniqueidentifier", 3, 0},
	{"SimulationCaseSetup", "Value"}: {"nvarchar", 4, 32},
	{"SimulationCaseSetup", "Quality"}: {"tinyint", 5, 0},
	{"SimulationReferenceData", "SimulationReferenceDataIdentifier"}: {"uniqueidentifier", 1, 0},
	{"SimulationReferenceData", "SimulationCaseIdentifier"}: {"uniqueidentifier", 2, 0},
	{"SimulationReferenceData", "InitializeTimeSegmentIdentifier"}: {"uniqueidentifier", 3, 0},
	{"SimulationReferenceData", "InitializeTime"}: {"datetime", 4, 0},
	{"SimulationReferenceData", "TimeSegmentIdentifier"}: {"uniqueidentifier", 5, 0},
	{"SimulationReferenceData", "IsFeed"}: {"bit", 6, 0},
	{"SimulationReferenceData", "IsContinueDataFeed"}: {"bit", 7, 0},
	{"SimulationReferenceData", "IsMatch"}: {"bit", 8, 0},
	{"SimulationReferenceData", "IsInitializeDynamics"}: {"bit", 9, 0},
	{"SimulationReferenceData", "IsFeedDataDelta"}: {"bit", 10, 0},
	{"SimulationReferenceDataLink", "SimulationReferenceDataIdentifier"}: {"uniqueidentifier", 1, 0},
	{"SimulationReferenceDataLink", "SimulationReferenceDataLinkIdentifier"}: {"uniqueidentifier", 2, 0},
	{"SimulationReferenceDataLink", "ProcessVariableIdentifier"}: {"uniqueidentifier", 3, 0},
	{"SimulationReferenceDataLink", "IOItemIdentifier"}: {"uniqueidentifier", 4, 0},
	{"SimulationReferenceDataLink", "IsInitialize"}: {"bit", 5, 0},
	{"SimulationReferenceDataLink", "IsFeed"}: {"bit", 6, 0},
	{"SimulationReferenceDataLink", "IsDelta"}: {"bit", 7, 0},
	{"SisoElements", "SisoElementIdentifier"}: {"uniqueidentifier", 1, 0},
	{"SisoElements", "Name"}: {"nvarchar", 2, 32},
	{"SisoElements", "Notes"}: {"nvarchar", 3, 2048},
	{"SisoElements", "SisoRelationIdentifier"}: {"uniqueidentifier", 4, 0},
	{"SisoElements", "SisoElementType"}: {"nvarchar", 5, 32},
	{"SisoElementValues", "ElementIdentifier"}: {"uniqueidentifier", 1, 0},
	{"SisoElementValues", "SisoElementValueType"}: {"nvarchar", 2, 50},
	{"SisoElementValues", "SisoElementValue"}: {"float", 3, 0},
	{"SisoRelation", "SisoRelationIdentifier"}: {"uniqueidentifier", 1, 0},
	{"SisoRelation", "RelationBlockIdentifier"}: {"uniqueidentifier", 2, 0},
	{"SisoRelation", "IsLegal"}: {"bit", 3, 0},
	{"SisoRelation", "IsDisturbance"}: {"bit", 4, 0},
	{"SisoRelation", "InputProcessVariableIdentifier"}: {"uniqueidentifier", 5, 0},
	{"SisoRelation", "OutputProcessVariableIdentifier"}: {"uniqueidentifier", 6, 0},
	{"TimeSegmentReferences", "TypeIdentifier"}: {"uniqueidentifier", 1, 0},
	{"TimeSegmentReferences", "TimeSegmentIdentifier"}: {"uniqueidentifier", 2, 0},
	{"TimeSegmentReferences", "TimeSegmentUserSelectionType"}: {"nvarchar", 3, 128},
	{"TimeSegments", "TimeSegmentIdentifier"}: {"uniqueidentifier", 1, 0},
	{"TimeSegments", "DataArrayTypeIdentifier"}: {"uniqueidentifier", 2, 0},
	{"TimeSegments", "StartTimeUtc"}: {"datetime", 3, 0},
	{"TimeSegments", "EndTimeUtc"}: {"datetime", 4, 0},
	{"TimeSegments", "FitIdentifier"}: {"uniqueidentifier", 5, 0},
	{"TraceLog", "TraceLogIdentity"}: {"int", 1, 0},
	{"TraceLog", "ImpactedItems"}: {"nvarchar", 2, 256},
	{"TraceLog", "ActionType"}: {"ntext", 3, 536870911},
	{"TraceLog", "ActionTotal"}: {"int", 4, 0},
	{"TraceLog", "PerformedBy"}: {"nvarchar", 5, 128},
	{"TraceLog", "PerformedDate"}: {"datetime", 6, 0},
	{"TraceLogActions", "TraceLogIdentity"}: {"int", 1, 0},
	{"TraceLogActions", "GroupIndex"}: {"int", 2, 0},
	{"TraceLogActions", "ModifiedType"}: {"nvarchar", 3, 32},
	{"TraceLogActions", "UndoLogic"}: {"ntext", 4, 536870911},
	{"TraceLogActions", "RedoLogic"}: {"ntext", 5, 536870911},
	{"UserParameter", "UserParameterId"}: {"uniqueidentifier", 1, 0},
	{"UserParameter", "EngineeringUnits"}: {"nvarchar", 2, 32},
	{"UserParameter", "UserParameterType"}: {"nvarchar", 3, 32},
	{"UserParameter", "IsOperatorEditable"}: {"bit", 4, 0},
	{"UserParameter", "DigitalStateId"}: {"uniqueidentifier", 5, 0},
	{"UserParameter", "SourceIOItemId"}: {"uniqueidentifier", 6, 0},
	{"UserParameter", "IsLocal"}: {"bit", 7, 0},
	{"VariableChartCellReference", "ChartCellIdentifier"}: {"uniqueidentifier", 1, 0},
	{"VariableChartCellReference", "VariableIdentifier"}: {"uniqueidentifier", 2, 0},
	{"VariableChartCellReference", "Visible"}: {"bit", 3, 0},
	{"VariableChartCellReference", "Color"}: {"int", 4, 0},
	{"VariableChartCellReference", "Highlighted"}: {"bit", 5, 0},
	{"VariableChartCellReference", "IsDigitalDataType"}: {"bit", 6, 0},
	{"VariableChartCellReference", "IsXAxis"}: {"bit", 7, 0},
	{"VariableChartCellReference", "AutoScaleY"}: {"bit", 8, 0},
	{"VariableChartCellReference", "ScaleYMaxVal"}: {"real", 9, 0},
	{"VariableChartCellReference", "ScaleYMinVal"}: {"real", 10, 0},
	{"VariableDatasourceTag", "ProcessVariableId"}: {"uniqueidentifier", 1, 0},
	{"VariableDatasourceTag", "DataSourceId"}: {"uniqueidentifier", 2, 0},
	{"VariableDatasourceTag", "TagName"}: {"nvarchar", 3, 255},
	{"VariableLabAssociations", "LabVariableId"}: {"uniqueidentifier", 1, 0},
	{"VariableLabAssociations", "AssociatedVariableId"}: {"uniqueidentifier", 2, 0},
	{"VariableReference", "VariableReferenceIdentifier"}: {"uniqueidentifier", 1, 0},
	{"VariableReference", "ParentObjId"}: {"uniqueidentifier", 2, 0},
	{"VariableReference", "ProcessVariableId"}: {"uniqueidentifier", 3, 0},
	{"VariableReference", "ReferenceType"}: {"nvarchar", 4, 32},
	{"VariableReference", "ItemSequenceIdentifier"}: {"uniqueidentifier", 5, 0},
	{"VariableReference", "TransformIdentifier"}: {"uniqueidentifier", 6, 0},
	{"VariableRole", "RoleIdentifier"}: {"uniqueidentifier", 1, 0},
	{"VariableRole", "ParentIdentifier"}: {"uniqueidentifier", 2, 0},
	{"VariableRole", "RoleType"}: {"nvarchar", 3, 32},
	{"VariableRole", "VariableReferenceIdentifier"}: {"uniqueidentifier", 4, 0},
	{"VariableTransform", "TransformIdentifier"}: {"uniqueidentifier", 1, 0},
	{"VariableTransform", "VariableIdentifier"}: {"uniqueidentifier", 2, 0},
	{"VariableTransform", "Formula"}: {"nvarchar", 3, 4000},
	{"VariableTransform", "Min"}: {"float", 4, 0},
	{"VariableTransform", "Max"}: {"float", 5, 0},
	{"VariableTransform", "PointNumber"}: {"int", 6, 0},
	{"WatchDog", "Identifier"}: {"uniqueidentifier", 1, 0},
	{"WatchDog", "ProcessorIdentifier"}: {"uniqueidentifier", 2, 0},
	{"WatchDogMVAssignment", "ProcessorId"}: {"uniqueidentifier", 1, 0},
	{"WatchDogMVAssignment", "VariableRoleIdentifier"}: {"uniqueidentifier", 2, 0},
	{"WatchDogMVAssignment", "WatchDogIdentifier"}: {"uniqueidentifier", 3, 0},
	{"WatchDogMVAssignment", "MoveVoilationBehaviour"}: {"int", 4, 0},
	{"WatchDogMVAssignment", "SlotNumber"}: {"int", 5, 0},
}
